name: create-version-pr

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (例: 1.0.0)'
        required: true

jobs:
  create-version-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - name: Update version
        run: |
          git config --global user.email "${GIT_AUTHOR_EMAIL}"
          git config --global user.name "${GIT_AUTHOR_NAME}"
          git switch -c ${BRANCH_NAME}
          yarn version --no-git-tag-version --new-version ${NEW_VERSION}
          git add -A && git commit -m "chore: v${NEW_VERSION}"
          git push -u origin ${BRANCH_NAME}
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          NEW_VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
      - name: Generate changelog
        id: generate-changelog
        run: |
          CHANGELOG=$($(yarn bin)/lerna-changelog --next-version ${NEW_VERSION})
          echo "::set-output name=changelog::${CHANGELOG}"
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ github.event.inputs.version }}
      - uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore: v${process.env.NEW_VERSION}`,
              head: process.env.BRANCH_NAME,
              base: "master",
              body: process.env.CHANGELOG
            })
        env:
          NEW_VERSION: ${{ github.event.inputs.version }}
          BRANCH_NAME: version/v${{ github.event.inputs.version }}
          CHANGELOG: ${{ steps.generate-changelog.outputs.changelog }}

